// Copyright (c) Microsoft Corporation
// The Microsoft Corporation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.Workspaces.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.Workspaces.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error launching workspace.
        /// </summary>
        internal static string plugin_workspaces_error_launching {
            get {
                return ResourceManager.GetString("plugin_workspaces_error_launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workspaces found.
        /// </summary>
        internal static string plugin_workspaces_error_no_workspaces {
            get {
                return ResourceManager.GetString("plugin_workspaces_error_no_workspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for workspaces.
        /// </summary>
        internal static string plugin_workspaces_fallback_display_title {
            get {
                return ResourceManager.GetString("plugin_workspaces_fallback_display_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for and launch PowerToys Workspaces.
        /// </summary>
        internal static string plugin_workspaces_description {
            get {
                return ResourceManager.GetString("plugin_workspaces_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerToys Workspaces.
        /// </summary>
        internal static string plugin_workspaces_name {
            get {
                return ResourceManager.GetString("plugin_workspaces_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workspace;ws.
        /// </summary>
        internal static string plugin_workspaces_search_tag {
            get {
                return ResourceManager.GetString("plugin_workspaces_search_tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        internal static string plugin_workspaces_workspace {
            get {
                return ResourceManager.GetString("plugin_workspaces_workspace", resourceCulture);
            }
        }
    }
}